language: python
python:
  - "3.4"
services: mysql
install:
  - pip install Django==1.9.8 mysqlclient==1.3.7 requests==2.10.0
script:
  - python3 qipr_approver/manage.py test qipr_approver/
  - coverage run --source approver/ manage.py test -v 2
after_success: coveralls